# Dev stuff
markdown:  rdiscount
safe:      true
lsi:       false
pygments:  true

# Site stuff
permalink: /:categories/:title
charset:   utf-8
baseurl:   /
url:       

# Specific stuff
version:      0.0.1
date:         0000-00-00
language:     en-GB
license:      v2.0. http://www.apache.org/licenses/LICENSE-2.0

name:         
name_short:   
tagline:      
color:        
email:        
copyright:    
google:       UA-XXXXXXXX-X
creator:      
publisher:    
keywords:     
description:  
twitter:      
twitter_card: 

### page details
# title
# description
# keywords
# graph_image
# graph_image_type
# graph_image_width
# graph_image_height