# Dev stuff
markdown:  rdiscount
safe:      true
lsi:       false
pygments:  true

# Site stuff
permalink: /:categories/:title
charset:   utf-8
baseurl:   /
url:       http://localhost:4000

# Specific stuff
version:      0.0.1
date:         0000-00-00
language:     en-GB
license:      v2.0. http://www.apache.org/licenses/LICENSE-2.0

name:         D-Blok Studios
name_short:   dblokstudios
tagline:      "We Make Beats. We Throw Parties. You Get Down"
color:        #000
email:        gregdaynes@gmail.com
copyright:    ©2013 D-Blok Studios. All rights reserved
google:       UA-XXXXXXXX-X
creator:      http://twitter.com/gregdaynes
publisher:    Gregory Daynes
keywords:     
description:  
twitter:      dblokstudios
twitter_card: summary

### page details
# title
# description
# keywords
# graph_image
# graph_image_type
# graph_image_width
# graph_image_height